### ISSUE TITLE
compleate install

### ISSUE THREAD

**Issue by makerio90** [smoove/cli-crypto-charts#2]
how do a make a complete install? i want to be able to run
```$ cryptocharts```
instead of
```$ cd ~/cli-crypto-charts && node cryptocharts.js```
ive tried copying the js file to my /bin/ dir, but that diddent work

**Comment by smoove** [comment]
The easiest way should be the following bash alias (add this line to your ~/.bashrc)

`alias cryptocharts="cd ~/cli-crypto-charts/ && node cryptocharts.js"`

Then you can execute `cryptocharts` from everywhere.

**Comment by makerio90** [comment]
```alias cryptocharts="cd ~/cli-crypto-charts/ && node cryptocharts.js && cd -"``` to auto cd back. thanks!
